### ISSUE TITLE
g2o compilation

### ISSUE THREAD

**Issue by anagno** [Beewe/ORB_SLAM2_Windows#5]
Hello,

I would like to use ORB_SLAM in windows and I came up to your repository. I was able to compile DBoW2 but unfortunatelly I was not able to compile compile g2o. Is is possible to give some more instructions on how to compile ORB_SLAM on windows?

Thank you in advance,

Vasilis

**Comment by M1234Thomas** [comment]
I am facing the same issue too. Can you post the solution if you have solved it. 

Thanks,
MT

**Comment by ahsteven** [comment]
Yes I get the error:

CMake Error at cmake_modules/FindBLAS.cmake:393 (message):
  A required library with BLAS API not found.  Please specify library
  location.
Call Stack (most recent call first):
  CMakeLists.txt:85 (FIND_PACKAGE)

What do you recommend for blas?

**Comment by petern3** [comment]
The original ORB_SLAM2 g2o CMakeLists.txt file has removed the following two lines, and it seems to work:

    -    FIND_PACKAGE(BLAS REQUIRED)
    -    FIND_PACKAGE(LAPACK REQUIRED)

I also removed the g2o `cmake_modules` folder, since it apparently isn't needed either. I think it works because BLAS and LAPACK are in Eigen3?

I've also created another issue (https://github.com/Beewe/ORB_SLAM2_Windows/issues/9) which has solutions to other problems you might come across that aren't necessarily g2o related.
